import type { Metadata } from "next";
import { Playfair_Display, Poppins } from "next/font/google";
import "./globals.css";
import Link from 'next/link'

const playfairDisplay = Playfair_Display({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700']
})

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
})

export const metadata: Metadata = {
  title: "DramaNest",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${playfairDisplay.className} ${poppins.className} antialiased`}
      >
        <header>
          <nav className="flex justify-around items-center text-white">
            <div className="logo">
              <h1 className="text-3xl">DramaNest</h1>
            </div>

            <div className="flex justify-between gap-8 font-medium text-base">
              <Link href={'/'}>Trending</Link>
              <Link href={'/k-dramas'}>K-dramas</Link>
              <Link href={'/faq'}>FAQ</Link>
            </div>

            <div className="bg-[#FF6B6B] text-white rounded-md login">
              <Link href={'/login'}>Login</Link>
            </div>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
